# Generated by Django 4.0 on 2022-01-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cart_color_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('PayPal', 'PayPal'), ('SSLcomerz', 'SSLcomerz')], default='Cash on Delivery', max_length=30),
        ),
    ]
